### Join Gold Standard Answers with Turk Answers

In [1]:
import pandas as pd

In [2]:
# Turk
lagos_turk = pd.read_csv("../data/mturk_new/lagos_mturk_2019_03_19.csv")
bangkok_turk = pd.read_csv("../data/mturk_new/bangkok_mturk_2019_03_11.csv")
jakarta_turk = pd.read_csv("../data/mturk_new/jakarta_mturk_2019_02_22.csv")

turk_all = pd.concat([lagos_turk, bangkok_turk, jakarta_turk])

# KO
lagos_ko = pd.read_csv("../data/ko/ko_lagos.csv")
lagos_ko = lagos_ko.iloc[:,range(0,10)]
lagos_ko['url'] = lagos_ko['url'].astype(int)
lagos_ko.loc[lagos_ko['url'] < 10, 'url2'] =  'lagos/img0_000' + lagos_ko['url'].astype(str) + '.jpg'
lagos_ko.loc[(lagos_ko['url'] < 100) & (lagos_ko['url'] >= 10), 'url2'] =  'lagos/img0_00' + lagos_ko['url'].astype(str) + '.jpg'
lagos_ko.loc[lagos_ko['url'] >= 100, 'url2'] =  'lagos/img0_0' + lagos_ko['url'].astype(str) + '.jpg'

bangkok_ko = pd.read_csv("../data/ko/ko_bangkok.csv")
bangkok_ko = bangkok_ko.iloc[:,range(0,10)]
bangkok_ko.loc[bangkok_ko['url'] < 10, 'url2'] =  'bangkok/img0_000' + bangkok_ko['url'].astype(str) + '.jpg'
bangkok_ko.loc[(bangkok_ko['url'] < 100) & (bangkok_ko['url'] >= 10), 'url2'] =  'bangkok/img0_00' + bangkok_ko['url'].astype(str) + '.jpg'
bangkok_ko.loc[bangkok_ko['url'] >= 100, 'url2'] =  'bangkok/img0_0' + bangkok_ko['url'].astype(str) + '.jpg'

jakarta_ko = pd.read_csv("../data/ko/ko_jakarta.csv")
jakarta_ko = jakarta_ko.iloc[:,range(0,10)]
jakarta_ko.loc[jakarta_ko['url'] < 10, 'url2'] =  'jakarta/img0_000' + jakarta_ko['url'].astype(str) + '.jpg'
jakarta_ko.loc[(jakarta_ko['url'] < 100) & (jakarta_ko['url'] >= 10), 'url2'] =  'jakarta/img0_00' + jakarta_ko['url'].astype(str) + '.jpg'
jakarta_ko.loc[jakarta_ko['url'] >= 100, 'url2'] =  'jakarta/img0_0' + jakarta_ko['url'].astype(str) + '.jpg'

ko_all = pd.concat([lagos_ko, bangkok_ko, jakarta_ko])

In [3]:
print(list(ko_all))
print(list(turk_all))

['url', 'sidewalk', 'Litter', 'pothole', 'clear markings', 'not clear markings', 'no markings', 'cracks', 'side of road markings', 'glitches', 'url2']
['HITId', 'HITTypeId', 'Title', 'Description', 'Keywords', 'Reward', 'CreationTime', 'MaxAssignments', 'RequesterAnnotation', 'AssignmentDurationInSeconds', 'AutoApprovalDelayInSeconds', 'Expiration', 'NumberOfSimilarHITs', 'LifetimeInSeconds', 'AssignmentId', 'WorkerId', 'AssignmentStatus', 'AcceptTime', 'SubmitTime', 'AutoApprovalTime', 'ApprovalTime', 'RejectionTime', 'RequesterFeedback', 'WorkTimeInSeconds', 'LifetimeApprovalRate', 'Last30DaysApprovalRate', 'Last7DaysApprovalRate', 'Input.id', 'Input.segment_id', 'Input.osm_id', 'Input.osm_name', 'Input.osm_type', 'Input.start_lat', 'Input.start_long', 'Input.end_lat', 'Input.end_long', 'Input.gsv_metadata', 'Input.copyright', 'Input.date', 'Input.location', 'Input.pano_id', 'Input.status', 'Input.url_img0', 'Input.url_img90', 'Input.url_img180', 'Input.url_img270', 'Answer.Do you see any of the following?.A paved sidewalk', 'Answer.Do you see any of the following?.Litter', 'Answer.annotatedResult.boundingBoxes', 'Answer.annotatedResult.inputImageProperties.height', 'Answer.annotatedResult.inputImageProperties.width', 'Answer.radios.clear', 'Answer.radios.no markings', 'Answer.radios.not clear', 'Approve', 'Reject']

In [4]:
turk_all['Input.url_img0'].head()

0    lagos/img0_0550.jpg
1    lagos/img0_0690.jpg
2    lagos/img0_0690.jpg
3    lagos/img0_0527.jpg
4    lagos/img0_0527.jpg
Name: Input.url_img0, dtype: object

In [5]:
ko_all['url2'].head()

0    lagos/img0_0003.jpg
1    lagos/img0_0010.jpg
2    lagos/img0_0016.jpg
3    lagos/img0_0029.jpg
4    lagos/img0_0054.jpg
Name: url2, dtype: object

In [6]:
ko_turk = ko_all.merge(turk_all, left_on='url2', right_on='Input.url_img0', how = 'left')

In [7]:
ko_turk.head()

,url,sidewalk,Litter,pothole,clear markings,not clear markings,no markings,cracks,side of road markings,glitches,...,Answer.Do you see any of the following?.A paved sidewalk,Answer.Do you see any of the following?.Litter,Answer.annotatedResult.boundingBoxes,Answer.annotatedResult.inputImageProperties.height,Answer.annotatedResult.inputImageProperties.width,Answer.radios.clear,Answer.radios.no markings,Answer.radios.not clear,Approve,Reject
0,3,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,...,False,True,"[{""height"":327,""label"":""Crack"",""left"":18,""top""...",640,640,True,False,False,NaN,NaN
1,3,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,...,True,False,"[{""height"":320,""label"":""Crack"",""left"":17,""top""...",640,640,False,True,False,NaN,NaN
2,10,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,...,False,False,[],640,640,False,True,False,NaN,NaN
3,10,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,...,True,False,"[{""height"":95,""label"":""Pothole"",""left"":232,""to...",640,640,False,True,False,NaN,NaN
4,16,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,...,True,False,"[{""height"":31,""label"":""Crack"",""left"":16,""top"":...",640,640,True,False,False,NaN,NaN

In [8]:
list(ko_turk)

['url',
 'sidewalk',
 'Litter',
 'pothole',
 'clear markings',
 'not clear markings',
 'no markings',
 'cracks',
 'side of road markings',
 'glitches',
 'url2',
 'HITId',
 'HITTypeId',
 'Title',
 'Description',
 'Keywords',
 'Reward',
 'CreationTime',
 'MaxAssignments',
 'RequesterAnnotation',
 'AssignmentDurationInSeconds',
 'AutoApprovalDelayInSeconds',
 'Expiration',
 'NumberOfSimilarHITs',
 'LifetimeInSeconds',
 'AssignmentId',
 'WorkerId',
 'AssignmentStatus',
 'AcceptTime',
 'SubmitTime',
 'AutoApprovalTime',
 'ApprovalTime',
 'RejectionTime',
 'RequesterFeedback',
 'WorkTimeInSeconds',
 'LifetimeApprovalRate',
 'Last30DaysApprovalRate',
 'Last7DaysApprovalRate',
 'Input.id',
 'Input.segment_id',
 'Input.osm_id',
 'Input.osm_name',
 'Input.osm_type',
 'Input.start_lat',
 'Input.start_long',
 'Input.end_lat',
 'Input.end_long',
 'Input.gsv_metadata',
 'Input.copyright',
 'Input.date',
 'Input.location',
 'Input.pano_id',
 'Input.status',
 'Input.url_img0',
 'Input.url_img90',
 'Input.url_img180',
 'Input.url_img270',
 'Answer.Do you see any of the following?.A paved sidewalk',
 'Answer.Do you see any of the following?.Litter',
 'Answer.annotatedResult.boundingBoxes',
 'Answer.annotatedResult.inputImageProperties.height',
 'Answer.annotatedResult.inputImageProperties.width',
 'Answer.radios.clear',
 'Answer.radios.no markings',
 'Answer.radios.not clear',
 'Approve',
 'Reject']

In [13]:
ko_turk.columns = [c.lower().replace(' ', '_') for c in ko_turk.columns]
ko_turk.rename(columns={"answer.do_you_see_any_of_the_following?.a_paved_sidewalk": "turk_sidewalk",
                       "answer.do_you_see_any_of_the_following?.litter": "turk_litter",
                       "answer.radios.no_markings": "turk_no_markings",
                       "answer.radios.not_clear": "turk_not_clear"}, inplace = True)

In [14]:
pd.crosstab(ko_turk.sidewalk, ko_turk.turk_sidewalk, margins=True)

turk_sidewalk  False  True  All
sidewalk
1.0               64   216  280
2.0              256    77  333
All              320   293  613

In [15]:
pd.crosstab(ko_turk.litter, ko_turk.turk_litter, margins=True)

turk_litter  False  True  All
litter
1.0             64    34   98
2.0            461    54  515
All            525    88  613

In [16]:
pd.crosstab(ko_turk.no_markings, ko_turk.turk_no_markings, margins=True)

turk_no_markings  False  True  All
no_markings
1.0                  68   242  310
2.0                 286    17  303
All                 354   259  613